spring.application.name=back-end

# -------------------------
# PostgreSQL Configuration
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=uday
spring.datasource.password=Uday@88717
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# -------------------------
# MongoDB Configuration
# -------------------------
spring.data.mongodb.uri=mongodb://uday:Uday%4088717@localhost:27017/prescriptions?authSource=admin

# -------------------------
# Redis Configuration
# -------------------------
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=Uday@88717

# -------------------------
# RabbitMQ Configuration
# -------------------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=uday
spring.rabbitmq.password=Uday@88717

# -------------------------
# Management / Actuator
# -------------------------
management.endpoint.health.show-details=always
management.health.db.enabled=true

# -------------------------
# JWT
# -------------------------
api.path=/
jwt.secret=L0rR1PZKypW+HnEMyBNOuh2f2Yy5+5DOt1GX7nQMhvHQB2zZUyQc+IGFEep7/iGI

# -------------------------
# Static Resources
# -------------------------
spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8